import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Ziima",
      email: "admin@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Neox",
      email: "admin2@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Fran",
      email: "user@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
    {
      name: "Nestor",
      email: "user2@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  productos: [
    {
      _id: "1",
      name: "Hellblazer #01",
      pages: 234,
      category: "mistery",
      image: "/images/product-1.jpg",
      price: 345,
      stock: 10,
      editorial: "DC",
      rating: 4.5,
      numReviews: 5,
      description: "Comic de Hellblazer tomo #1 de la editorial DC Comics",
    },
    {
      _id: "2",
      name: "Batman año cero",
      pages: 250,
      category: "detective",
      image: "/images/product-2.jpg",
      price: 380,
      stock: 15,
      editorial: "DC",
      rating: 5,
      numReviews: 20,
      description: "Comic de Batman año cero de la editorial DC Comics",
    },
    {
      _id: "3",
      name: "Batman año uno",
      pages: 305,
      category: "detective",
      image: "/images/product-3.jpg",
      price: 425,
      stock: 0,
      editorial: "DC",
      rating: 3.5,
      numReviews: 15,
      description: "Comic de Batman año uno de la editorial DC Comics",
    },
    {
      _id: "4",
      name: "Hellblazer #02",
      pages: 334,
      category: "mistery",
      image: "/images/product-4.jpg",
      price: 445,
      stock: 20,
      editorial: "DC",
      rating: 5,
      numReviews: 13,
      description: "Comic de Hellblazer tomo #2 de la editorial DC Comics",
    },
    {
      _id: "5",
      name: "Hellblazer #03",
      pages: 224,
      category: "mistery",
      image: "/images/product-5.jpg",
      price: 325,
      stock: 5,
      editorial: "DC",
      rating: 4,
      numReviews: 10,
      description: "Comic de Hellblazer tomo #3 de la editorial DC Comics",
    },
  ],
};
export default data;
